# Price:
#  * Price is always in USD per 1 million input/output tokens.
#  * If no price is directly available, we use the prices from https://www.together.ai/.
# Quality:
#  * We use LiveBench (https://livebench.ai/) as far as results are available.
#  * We take the "Global Average".
#  * The benchmark is versioned and it only makes sense to compare scores at the same version. We use 2025-04-25.

####### Google Gemini Models #######

[[model]]
display_name = "gemini-2.5-pro"
model_class = "premium"
modalities = ["text", "image", "video", "audio", "document"]
price = { input = 1.25, output = 10.0 }
release_year = 2025
quality.livebench = 78.99
supported_by = [
    { system = "bigquery", endpoint = "gemini-2.5-pro" },
    { system = "lotus", endpoint = "gemini-2.5-pro" }
]

[[model]]
display_name = "gemini-2.5-flash"
model_class = "medium"
modalities = ["text", "image", "video", "audio", "document"]
price = { input = 0.30, output = 2.50, audio = 1.00 }
release_year = 2025
quality.livebench = 71.98
supported_by = [
    { system = "bigquery", endpoint = "gemini-2.5-flash" },
    { system = "lotus", endpoint = "gemini-2.5-flash" }
]

[[model]]
display_name = "gemini-2.5-flash-lite"
model_class = ""
modalities = ["text", "image", "video", "audio", "document"]
price = { input = 0.10, output = 0.40, audio = 0.30 }
release_year = 2025
quality.livebench = 57.53 # only latest available, so hard to compare to other models
supported_by = [
    { system = "bigquery", endpoint = "gemini-2.5-flash-lite" },
    { system = "lotus", endpoint = "gemini-2.5-flash-lite" }
]

[[model]]
display_name = "gemini-2.0-flash"
model_class = ""
modalities = ["text", "image", "video", "audio", "document"]
price = { input = 0.15, output = 0.60, audio = 1.00 }
release_year = 2024
quality.livebench = 54.89 # only older available, so hard to compare to other models
supported_by = [
    { system = "bigquery", endpoint = "gemini-2.0-flash" },
    { system = "lotus", endpoint = "gemini-2.0-flash" }
]

[[model]]
display_name = "gemini-2.0-flash-lite"
model_class = "cheap"
modalities = ["text", "image", "video", "audio", "document"]
price = { input = 0.075, output = 0.30 }
release_year = 2025
quality.livebench = 53.75
supported_by = [
    { system = "bigquery", endpoint = "gemini-2.0-flash-lite" },
    { system = "lotus", endpoint = "gemini-2.0-flash-lite" }
]

####### OpenAI Models #######

[[model]]
display_name = "gpt-4o"
model_class = "premium"
modalities = ["text", "image", "document"]
price = { input = 2.50, output = 10.0 }
release_year = 2024
quality.livebench = 61.65
supported_by = [
    { system = "palimpzest", endpoint = "GPT_4o" },
    { system = "lotus", endpoint = "gpt-4o" }
]

[[model]]
display_name = "gpt-4o-mini"
model_class = ""
modalities = ["text", "image", "document"]
price = { input = 0.15, output = 0.60 }
release_year = 2024
quality.livebench = 43.41
supported_by = [
    { system = "palimpzest", endpoint = "GPT_4o_MINI" },
    { system = "lotus", endpoint = "gpt-4o-mini" }
]

[[model]]
display_name = "gpt-4.1"
model_class = ""
modalities = ["text", "image", "document"]
price = { input = 2.00, output = 8.00 }
release_year = 2024
quality.livebench = 62.99
supported_by = [
    { system = "snowflake-cortext", endpoint = "openai-gpt-4.1" }
]

[[model]]
display_name = "o4-mini"
model_class = ""
modalities = ["text", "image", "document"]
price = { input = 1.10, output = 4.40 }
release_year = 2025
quality.livebench = 74.40
supported_by = [
    { system = "snowflake-cortext", endpoint = "openai-o4-mini" }
]

####### Llama Models #######

[[model]]
display_name = "llama-3.1-8b-turbo"
model_class = ""
modalities = ["text"]
model_size = "8B"
price = { input = 0.18, output = 0.18 } # (together.ai)
release_year = 2024
quality.livebench = 24.95 # only older available, so hard to compare to other models
supported_by = [
    { system = "palimpzest", endpoint = "LLAMA3_1_8B" },
    { system = "lotus", endpoint = "together_ai/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo" },
    { system = "snowflake-cortex", endpoint = "llama3.1-8b" }
]

[[model]]
display_name = "llama-3.2-3b-turbo"
model_class = ""
modalities = ["text"]
model_size = "3B"
price = { input = 0.06, output = 0.06 } # (together.ai)
release_year = 2024
supported_by = [
    { system = "palimpzest", endpoint = "LLAMA3_2_3B" },
    { system = "lotus", endpoint = "together_ai/meta-llama/Llama-3.2-3B-Instruct-Turbo" }
]

[[model]]
display_name = "llama-3.2-90b-vision"
model_class = ""
modalities = ["text", "images"]
model_size = "90B"
price = { input = 1.20, output = 1.20 } # (together.ai)
release_year = 2024
supported_by = [
    { system = "palimpzest", endpoint = "LLAMA3_2_90B_V" },
    { system = "lotus", endpoint = "vertex_ai/meta/llama-3.2-90b-vision-instruct-maas" }
]

[[model]]
display_name = "llama-3.3-70b-turbo"
model_class = ""
modalities = ["text"]
model_size = "70B"
price = { input = 0.88, output = 0.88 } # (together.ai)
release_year = 2024
quality.livebench = 48.86
supported_by = [
    { system = "palimpzest", endpoint = "LLAMA3_3_70B" },
    { system = "lotus", endpoint = "together_ai/meta-llama/Llama-3.3-70B-Instruct-Turbo" },
    { system = "snowflake-cortex", endpoint = "llama3.3-70b" }
]

[[model]]
display_name = "llama-4-maverick"
model_class = ""
modalities = ["text", "image"]
model_size = "400B"
price = { input = 0.27, output = 0.85 } # (together.ai)
release_year = 2025
quality.livebench = 55.19
supported_by = [
    { system = "snowflake-cortex", endpoint = "llama4-maverick" }
]

[[model]]
display_name = "llama-4-scout"
model_class = ""
modalities = ["text", "image"]
model_size = "109B"
price = { input = 0.18, output = 0.59 } # (together.ai)
release_year = 2025
supported_by = [
    { system = "snowflake-cortex", endpoint = "llama4-scout" }
]

####### DeepSeek Models #######

[[model]]
display_name = "deepseek-v3"
model_class = ""
modalities = ["text"]
model_size = "671B"
price = { input = 1.25, output = 1.25 } # (together.ai)
release_year = 2024
quality.livebench = 62.82
supported_by = [
    { system = "palimpzest", endpoint = "DEEPSEEK_V3" },
    { system = "lotus", endpoint = "together_ai/deepseek-ai/DeepSeek-V3" }
]

[[model]]
display_name = "deepseek-r1"
model_class = "premium"
modalities = ["text"]
model_size = "685B"
price = { input = 0.27, output = 1.10 }  # per DeepSeeks offering (there is also a discount during certain hours. together.ai costs 3$in/7$out)
release_year = 2025
quality.livebench = 76.80
supported_by = [
    { system = "snowflake-cortex", endpoint = "deepseek-r1" }
]

[[model]]
display_name = "deepseek-r1-distill-qwen-1.5b"
model_class = "cheap"
modalities = ["text"]
model_size = "1.5B"
price = { input = 0.18, output = 0.18 } # (together.ai)
release_year = 2025
supported_by = [
    { system = "palimpzest", endpoint = "DEEPSEEK_R1_DISTILL_QWEN_1_5B" },
    { system = "lotus", endpoint = "nscale/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B" }
]

####### Anthropic Models #######

[[model]]
display_name = "claude-4-opus"
model_class = "premium"
modalities = ["text", "image"]
price = { input = 15.0, output = 75 }
release_year = 2025
quality.livebench = 71.52
supported_by = [
    { system = "snowflake-cortex", endpoint = "claude-4-opus" }
]

[[model]]
display_name = "claude-4-sonnet"
model_class = ""
modalities = ["text", "image"]
price = { input = 3, output = 15 }
release_year = 2025
quality.livebench = 69.65
supported_by = [
    { system = "snowflake-cortex", endpoint = "claude-4-sonnet" }
]

[[model]]
display_name = "claude-3-7-sonnet"
model_class = ""
modalities = ["text", "image"]
price = { input = 3, output = 15 }
release_year = 2025
quality.livebench = 64.62
supported_by = [
    { system = "snowflake-cortex", endpoint = "claude-3-7-sonnet" }
]

[[model]]
display_name = "claude-3-5-sonnet"
model_class = ""
modalities = ["text", "image"]
price = { input = 3, output = 15 }
release_year = 2025
quality.livebench = 57.94
supported_by = [
    { system = "snowflake-cortex", endpoint = "claude-3-5-sonnet" }
]


####### Other Models #######

[[model]]
display_name = "mixtral-8x7b-instruct"
model_class = ""
modalities = ["text"]
model_size = "46B"
price = { input = 0.60, output = 0.60 } # (together.ai)
release_year = 2023
quality.livebench = 22.73 # only older available, so hard to compare to other models
supported_by = [
    { system = "palimpzest", endpoint = "MIXTRAL" },
    { system = "lotus", endpoint = "together_ai/mistralai/Mixtral-8x7B-Instruct-v0.1" },
    { system = "snowflake-cortex", endpoint = "mixtral-8x7b" }
]
